# Generated by Django 3.0.6 on 2020-10-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminaccount',
            name='last_name',
        ),
    ]
